---
- name: check if mysqld exporter exist 
  stat: 
    path: "{{ mysqld_exporter_bin }}"
  register: __check_mysqld_exporter_present

- name: create mysqld exporter user 
  user:
    name: "{{ mysqld_exporter_user }}"
    group: "{{ mysqld_exporter_group }}"
    append: true
    shell: /usr/sbin/nologin
    system: true
    create_home: false

- name: create mysqld exporter config directory 
  file:
    path: "{{ mysqld_exporter_dir_conf }}"
    state: directory
    owner: "{{ mysqld_exporter_user }}"
    group: "{{ mysqld_exporter_group }}"

- name: download and unzip mysqld exporter if not exist
  unarchive:
    src: "https://github.com/prometheus/mysqld_exporter/releases/download/v{{ mysqld_exporter_version }}/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64.tar.gz"
    dest: /tmp/
    remote_src: yes
    validate_certs: no
  when: __check_mysqld_exporter_present.stat.exists == false

- name: move the binary to the final destination
  copy:
    src: "/tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/mysqld_exporter"
    dest: "{{ mysqld_exporter_bin }}"
    owner: "{{ mysqld_exporter_user }}"
    groups: "{{ mysqld_exporter_group }}"
    mode: 0755
    remote_src: yes
  when: __check_mysqld_exporter_present.stat.exists == false

- name: clean 
  file:
    path: /tmp/mysqld_exporter-{{ mysqld_exporter_version }}.linux-amd64/ 
    state: absent

- name: create mysql user
  mysql_user:
    login_unix_socket: /var/run/mysqld/mysqld.sock
    name: exporter
    password: password
    priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
    host: localhost
    state: present
  tags: [ never, mysql_user ]

- name: configure mysqld exporter
  template:
    src: .mysqld_exporter.cnf.j2
    dest: /etc/.mysqld_exporter.cnf
    owner: root
    group: "{{ mysqld_exporter_group }}"
    mode: 0755
  
- name: install service
  template: 
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld_exporter.service
    mode: 0755
  notify: reload_daemon_and_restart_mysqld_exporter

- meta: flush_handlers